name: "base-component"
api:
  version: 20170811
  port: "8080"
  # RSA Public Key used for JWT validation
  public_key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4HA/WopDR0IlMktWiM8N
    mYhCNb0pdvyLy12v9q+mH5C4wNhfb/ZE3X3ceddQFzn9TJO+GiDGbLs1dFn3WKtY
    Ww6Ju36FLYc2iMpbdlsQ9eksRZwG0QfjeZXokVurKyn82INUIe5oBrqB+ADl+5xS
    EkYTXlK5gvwAH1diyEuYlHq6F5+EY8SOzyrZf/pwjVO2BdxGdBfUqoKIBgKd+ZxJ
    wfmyon6rgmikxU9++LSsMNBeJcYtfx2W9/6hK5rC9MiZ7qeR5jU6yMdUMNQKeJSN
    Y9kK7E40YgZsI/vW/5HhhkdMMK2wd4p98n+AYXY1D3IL7dextKgD0owTvqmT08M0
    vQIDAQAB
    -----END PUBLIC KEY-----
workers:
  number: 100
  total_queue_size: 5000
  heartbeat_seconds: 15
monitoring:
  prometheus: false
logging:
  elasticsearch: false
  endpoint: "http://127.0.0.1:9200"
