package util

var (

	// SoftwareVersion is the git version identifier generated by: git describe --always.
	SoftwareVersion = "dev"

	// APIVersion is the git version identifier generated by: git describe --always.
	APIVersion = "dev"

	// ReleaseTimestamp is a timestamp for when the application was tagged for the release.
	ReleaseTimestamp = "N/A"

	// Build is a timestamp for when the application was built.
	Build = "N/A"
)
