@port = 8080
@hostname = http://127.0.0.1
@contentType = application/json

@host = {{hostname}}:{{port}}

###

# @name jobRef
POST {{host}}/jobs
Content-Type: {{contentType}}

{
	"message": "Order Tacos!"
}

###

@jobID = {{jobRef.response.body.$.jobID}}

# @name jobState
GET {{host}}/jobs/{{jobID}}
Content-Type: {{contentType}}

# ###

# # @name jobsState
# GET {{host}}/jobs
# Content-Type: {{contentType}}

# ###

# # @name removeJob
# DELETE  {{host}}/jobs/{{jobID}}
# Content-Type: {{contentType}}
